DROP TABLE T_DADOS_BANCARIOS_ONG  CASCADE CONSTRAINTS;
DROP TABLE T_DOACOES_ONG  CASCADE CONSTRAINTS;
DROP TABLE T_DOADOR  CASCADE CONSTRAINTS;
DROP TABLE T_ENDERECO_ONG  CASCADE CONSTRAINTS;
DROP TABLE T_IMG_ONG  CASCADE CONSTRAINTS;
DROP TABLE T_ONG  CASCADE CONSTRAINTS;